// Generated by Bisonc++ V4.10.01 on Fri, 03 Mar 2017 15:37:29 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {295, 2}, // 1: program ->  declaration_list procedure_definition
     {296, 1}, // 2: declaration_list ->  procedure_declaration
     {296, 2}, // 3: declaration_list ->  variable_declaration_list procedure_declaration
     {296, 2}, // 4: declaration_list ->  procedure_declaration variable_declaration_list
     {298, 5}, // 5: procedure_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {297, 9}, // 6: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 statement_list '}'
     {299, 0}, // 7: #0001 ->  <empty>
     {300, 0}, // 8: #0002 ->  <empty>
     {301, 0}, // 9: optional_variable_declaration_list ->  <empty>
     {301, 1}, // 10: optional_variable_declaration_list ->  variable_declaration_list
     {302, 1}, // 11: variable_declaration_list ->  variable_declaration
     {302, 2}, // 12: variable_declaration_list ->  variable_declaration_list variable_declaration
     {303, 2}, // 13: variable_declaration (';') ->  declaration ';'
     {304, 2}, // 14: declaration (INTEGER) ->  INTEGER var_list
     {304, 2}, // 15: declaration (FLOAT) ->  FLOAT var_list
     {305, 1}, // 16: var_list (NAME) ->  NAME
     {305, 3}, // 17: var_list (',') ->  var_list ',' NAME
     {306, 0}, // 18: statement_list ->  <empty>
     {306, 2}, // 19: statement_list ->  statement_list statement
     {307, 1}, // 20: statement ->  assignment_statement
     {307, 3}, // 21: statement ('{') ->  '{' statement_list '}'
     {307, 5}, // 22: statement (WHILE) ->  WHILE '(' boolean_expr ')' statement
     {307, 5}, // 23: statement (IFX) ->  IF '(' boolean_expr ')' statement
     {307, 7}, // 24: statement (IF) ->  IF '(' boolean_expr ')' statement ELSE statement
     {307, 7}, // 25: statement (DO) ->  DO statement WHILE '(' boolean_expr ')' ';'
     {308, 4}, // 26: assignment_statement (ASSIGN) ->  variable ASSIGN arith_expression ';'
     {309, 3}, // 27: arith_expression ('+') ->  arith_expression '+' arith_expression
     {309, 3}, // 28: arith_expression ('-') ->  arith_expression '-' arith_expression
     {309, 3}, // 29: arith_expression ('*') ->  arith_expression '*' arith_expression
     {309, 3}, // 30: arith_expression ('/') ->  arith_expression '/' arith_expression
     {309, 3}, // 31: arith_expression ('(') ->  '(' arith_expression ')'
     {309, 2}, // 32: arith_expression (UMINUS) ->  '-' arith_expression
     {309, 1}, // 33: arith_expression ->  expression_term
     {309, 5}, // 34: arith_expression (SAATH) ->  boolean_expr '?' arith_expression ':' arith_expression
     {310, 3}, // 35: relational_expr (LE) ->  arith_expression LE arith_expression
     {310, 3}, // 36: relational_expr (GE) ->  arith_expression GE arith_expression
     {310, 3}, // 37: relational_expr (LEQ) ->  arith_expression LEQ arith_expression
     {310, 3}, // 38: relational_expr (GEQ) ->  arith_expression GEQ arith_expression
     {310, 3}, // 39: relational_expr (EQ) ->  arith_expression EQ arith_expression
     {310, 3}, // 40: relational_expr (NEQ) ->  arith_expression NEQ arith_expression
     {311, 3}, // 41: boolean_expr (OR) ->  boolean_expr OR boolean_expr
     {311, 3}, // 42: boolean_expr (AND) ->  boolean_expr AND boolean_expr
     {311, 2}, // 43: boolean_expr (NOT) ->  NOT boolean_expr
     {311, 3}, // 44: boolean_expr ('(') ->  '(' boolean_expr ')'
     {311, 1}, // 45: boolean_expr ->  relational_expr
     {312, 1}, // 46: expression_term ->  variable
     {312, 1}, // 47: expression_term ->  constant
     {313, 1}, // 48: variable (NAME) ->  NAME
     {314, 1}, // 49: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {314, 1}, // 50: constant (DOUBLE_NUMBER) ->  DOUBLE_NUMBER
     {315, 1}, // 51: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 10} },                             
    { {       295}, {  1} }, // program                  
    { {       296}, {  2} }, // declaration_list         
    { {       298}, {  3} }, // procedure_declaration    
    { {       302}, {  4} }, // variable_declaration_list
    { {       264}, {  5} }, // VOID                     
    { {       303}, {  6} }, // variable_declaration     
    { {       304}, {  7} }, // declaration              
    { {       261}, {  8} }, // INTEGER                  
    { {       262}, {  9} }, // FLOAT                    
    { {         0}, {  0} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  3} },                        
    { {       297}, { 10} }, // procedure_definition
    { {       258}, { 11} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                             
    { {     302}, { 12} }, // variable_declaration_list
    { {     303}, {  6} }, // variable_declaration     
    { {     304}, {  7} }, // declaration              
    { {     261}, {  8} }, // INTEGER                  
    { {     262}, {  9} }, // FLOAT                    
    { {       0}, { -2} },                             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       298}, { 13} }, // procedure_declaration
    { {       303}, { 14} }, // variable_declaration 
    { {       264}, {  5} }, // VOID                 
    { {       304}, {  7} }, // declaration          
    { {       261}, {  8} }, // INTEGER              
    { {       262}, {  9} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 16} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       305}, { 17} }, // var_list
    { {       258}, { 18} }, // NAME    
    { {         0}, {  0} },            
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       305}, { 19} }, // var_list
    { {       258}, { 18} }, // NAME    
    { {         0}, {  0} },            
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 20} }, // '('
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  5} },                        
    { {     303}, { 14} }, // variable_declaration
    { {     304}, {  7} }, // declaration         
    { {     261}, {  8} }, // INTEGER             
    { {     262}, {  9} }, // FLOAT               
    { {       0}, { -4} },                        
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 21} }, // '('
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  22} }, // ','
    { {       0}, { -14} },       
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_19[] =
{
    { { REQ_DEF}, {   2} },       
    { {      44}, {  22} }, // ','
    { {       0}, { -15} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 23} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 24} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 25} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_23[] =
{
    { { DEF_RED}, {  2} },         
    { {     299}, { 26} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 27} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_25[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 28} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_28[] =
{
    { { REQ_DEF}, {  7} },                                      
    { {     301}, { 29} }, // optional_variable_declaration_list
    { {     302}, { 30} }, // variable_declaration_list         
    { {     303}, {  6} }, // variable_declaration              
    { {     304}, {  7} }, // declaration                       
    { {     261}, {  8} }, // INTEGER                           
    { {     262}, {  9} }, // FLOAT                             
    { {       0}, { -9} },                                      
};

SR__ s_29[] =
{
    { { DEF_RED}, {  2} },         
    { {     300}, { 31} }, // #0002
    { {       0}, { -8} },         
};

SR__ s_30[] =
{
    { { REQ_DEF}, {   5} },                        
    { {     303}, {  14} }, // variable_declaration
    { {     304}, {   7} }, // declaration         
    { {     261}, {   8} }, // INTEGER             
    { {     262}, {   9} }, // FLOAT               
    { {       0}, { -10} },                        
};

SR__ s_31[] =
{
    { { DEF_RED}, {   2} },                  
    { {     306}, {  32} }, // statement_list
    { {       0}, { -18} },                  
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, { 10} },                        
    { {       125}, { 33} }, // '}'                 
    { {       307}, { 34} }, // statement           
    { {       308}, { 35} }, // assignment_statement
    { {       123}, { 36} }, // '{'                 
    { {       266}, { 37} }, // WHILE               
    { {       265}, { 38} }, // IF                  
    { {       267}, { 39} }, // DO                  
    { {       313}, { 40} }, // variable            
    { {       258}, { 41} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_35[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_36[] =
{
    { { DEF_RED}, {   2} },                  
    { {     306}, {  42} }, // statement_list
    { {       0}, { -18} },                  
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 43} }, // '('
    { {         0}, {  0} },       
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 44} }, // '('
    { {         0}, {  0} },       
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, {  9} },                        
    { {       307}, { 45} }, // statement           
    { {       308}, { 35} }, // assignment_statement
    { {       123}, { 36} }, // '{'                 
    { {       266}, { 37} }, // WHILE               
    { {       265}, { 38} }, // IF                  
    { {       267}, { 39} }, // DO                  
    { {       313}, { 40} }, // variable            
    { {       258}, { 41} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 46} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 10} },                        
    { {       125}, { 47} }, // '}'                 
    { {       307}, { 34} }, // statement           
    { {       308}, { 35} }, // assignment_statement
    { {       123}, { 36} }, // '{'                 
    { {       266}, { 37} }, // WHILE               
    { {       265}, { 38} }, // IF                  
    { {       267}, { 39} }, // DO                  
    { {       313}, { 40} }, // variable            
    { {       258}, { 41} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 48} }, // boolean_expr    
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {       309}, { 52} }, // arith_expression
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 59} }, // boolean_expr    
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {       309}, { 52} }, // arith_expression
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       266}, { 60} }, // WHILE
    { {         0}, {  0} },         
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 61} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_47[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 63} }, // ')'
    { {       269}, { 64} }, // OR 
    { {       270}, { 65} }, // AND
    { {        63}, { 66} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 67} }, // boolean_expr    
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {       309}, { 52} }, // arith_expression
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 68} }, // boolean_expr    
    { {       309}, { 69} }, // arith_expression
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_51[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, { 11} },       
    { {       273}, { 70} }, // LE 
    { {       275}, { 71} }, // GE 
    { {       274}, { 72} }, // LEQ
    { {       276}, { 73} }, // GEQ
    { {       271}, { 74} }, // EQ 
    { {       272}, { 75} }, // NEQ
    { {        43}, { 76} }, // '+'
    { {        45}, { 77} }, // '-'
    { {        42}, { 78} }, // '*'
    { {        47}, { 79} }, // '/'
    { {         0}, {  0} },       
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 80} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -33} }, 
};

SR__ s_55[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_56[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_57[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -49} }, 
};

SR__ s_58[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -50} }, 
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 81} }, // ')'
    { {       269}, { 64} }, // OR 
    { {       270}, { 65} }, // AND
    { {        63}, { 66} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 82} }, // '('
    { {         0}, {  0} },       
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 12} },       
    { {        59}, { 83} }, // ';'
    { {        43}, { 76} }, // '+'
    { {        45}, { 77} }, // '-'
    { {        42}, { 78} }, // '*'
    { {        47}, { 79} }, // '/'
    { {       273}, { 70} }, // LE 
    { {       275}, { 71} }, // GE 
    { {       274}, { 72} }, // LEQ
    { {       276}, { 73} }, // GEQ
    { {       271}, { 74} }, // EQ 
    { {       272}, { 75} }, // NEQ
    { {         0}, {  0} },       
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  4} },       
    { {        63}, { 66} }, // '?'
    { {       269}, { 64} }, // OR 
    { {       270}, { 65} }, // AND
    { {         0}, {  0} },       
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  9} },                        
    { {       307}, { 84} }, // statement           
    { {       308}, { 35} }, // assignment_statement
    { {       123}, { 36} }, // '{'                 
    { {       266}, { 37} }, // WHILE               
    { {       265}, { 38} }, // IF                  
    { {       267}, { 39} }, // DO                  
    { {       313}, { 40} }, // variable            
    { {       258}, { 41} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 85} }, // boolean_expr    
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {       309}, { 52} }, // arith_expression
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       311}, { 86} }, // boolean_expr    
    { {       278}, { 49} }, // NOT             
    { {        40}, { 50} }, // '('             
    { {       310}, { 51} }, // relational_expr 
    { {       309}, { 52} }, // arith_expression
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 87} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -43} }, 
};

SR__ s_68[] =
{
    { { REQ_TOKEN}, {  5} },       
    { {        41}, { 88} }, // ')'
    { {       269}, { 64} }, // OR 
    { {       270}, { 65} }, // AND
    { {        63}, { 66} }, // '?'
    { {         0}, {  0} },       
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, { 12} },       
    { {        41}, { 89} }, // ')'
    { {        43}, { 76} }, // '+'
    { {        45}, { 77} }, // '-'
    { {        42}, { 78} }, // '*'
    { {        47}, { 79} }, // '/'
    { {       273}, { 70} }, // LE 
    { {       275}, { 71} }, // GE 
    { {       274}, { 72} }, // LEQ
    { {       276}, { 73} }, // GEQ
    { {       271}, { 74} }, // EQ 
    { {       272}, { 75} }, // NEQ
    { {         0}, {  0} },       
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 90} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 91} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 92} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 93} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_74[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 94} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 95} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 96} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 97} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 98} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, { 13} },                    
    { {       309}, { 99} }, // arith_expression
    { {        40}, { 50} }, // '('             
    { {        45}, { 53} }, // '-'             
    { {       312}, { 54} }, // expression_term 
    { {       311}, { 62} }, // boolean_expr    
    { {       313}, { 55} }, // variable        
    { {       314}, { 56} }, // constant        
    { {       278}, { 49} }, // NOT             
    { {       310}, { 51} }, // relational_expr 
    { {       258}, { 41} }, // NAME            
    { {       257}, { 57} }, // INTEGER_NUMBER  
    { {       259}, { 58} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_80[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {   9} },                        
    { {       307}, { 100} }, // statement           
    { {       308}, {  35} }, // assignment_statement
    { {       123}, {  36} }, // '{'                 
    { {       266}, {  37} }, // WHILE               
    { {       265}, {  38} }, // IF                  
    { {       267}, {  39} }, // DO                  
    { {       313}, {  40} }, // variable            
    { {       258}, {  41} }, // NAME                
    { {         0}, {   0} },                        
};

SR__ s_82[] =
{
    { { REQ_TOKEN}, {  13} },                    
    { {       311}, { 101} }, // boolean_expr    
    { {       278}, {  49} }, // NOT             
    { {        40}, {  50} }, // '('             
    { {       310}, {  51} }, // relational_expr 
    { {       309}, {  52} }, // arith_expression
    { {        45}, {  53} }, // '-'             
    { {       312}, {  54} }, // expression_term 
    { {       313}, {  55} }, // variable        
    { {       314}, {  56} }, // constant        
    { {       258}, {  41} }, // NAME            
    { {       257}, {  57} }, // INTEGER_NUMBER  
    { {       259}, {  58} }, // DOUBLE_NUMBER   
    { {         0}, {   0} },                    
};

SR__ s_83[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_84[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   2} },       
    { {     270}, {  65} }, // AND
    { {       0}, { -41} },       
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -42} }, 
};

SR__ s_87[] =
{
    { { REQ_TOKEN}, {  12} },       
    { {        58}, { 102} }, // ':'
    { {        43}, {  76} }, // '+'
    { {        45}, {  77} }, // '-'
    { {        42}, {  78} }, // '*'
    { {        47}, {  79} }, // '/'
    { {       273}, {  70} }, // LE 
    { {       275}, {  71} }, // GE 
    { {       274}, {  72} }, // LEQ
    { {       276}, {  73} }, // GEQ
    { {       271}, {  74} }, // EQ 
    { {       272}, {  75} }, // NEQ
    { {         0}, {   0} },       
};

SR__ s_88[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_89[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_90[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -35} },       
};

SR__ s_91[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -36} },       
};

SR__ s_92[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -37} },       
};

SR__ s_93[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -38} },       
};

SR__ s_94[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -39} },       
};

SR__ s_95[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -40} },       
};

SR__ s_96[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {       0}, { -27} },       
};

SR__ s_97[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {       0}, { -28} },       
};

SR__ s_98[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_99[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_100[] =
{
    { { REQ_DEF}, {   2} },        
    { {     280}, { 103} }, // ELSE
    { {       0}, { -23} },        
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {   5} },       
    { {        41}, { 104} }, // ')'
    { {       269}, {  64} }, // OR 
    { {       270}, {  65} }, // AND
    { {        63}, {  66} }, // '?'
    { {         0}, {   0} },       
};

SR__ s_102[] =
{
    { { REQ_TOKEN}, {  13} },                    
    { {       309}, { 105} }, // arith_expression
    { {        40}, {  50} }, // '('             
    { {        45}, {  53} }, // '-'             
    { {       312}, {  54} }, // expression_term 
    { {       311}, {  62} }, // boolean_expr    
    { {       313}, {  55} }, // variable        
    { {       314}, {  56} }, // constant        
    { {       278}, {  49} }, // NOT             
    { {       310}, {  51} }, // relational_expr 
    { {       258}, {  41} }, // NAME            
    { {       257}, {  57} }, // INTEGER_NUMBER  
    { {       259}, {  58} }, // DOUBLE_NUMBER   
    { {         0}, {   0} },                    
};

SR__ s_103[] =
{
    { { REQ_TOKEN}, {   9} },                        
    { {       307}, { 106} }, // statement           
    { {       308}, {  35} }, // assignment_statement
    { {       123}, {  36} }, // '{'                 
    { {       266}, {  37} }, // WHILE               
    { {       265}, {  38} }, // IF                  
    { {       267}, {  39} }, // DO                  
    { {       313}, {  40} }, // variable            
    { {       258}, {  41} }, // NAME                
    { {         0}, {   0} },                        
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {   2} },       
    { {        59}, { 107} }, // ';'
    { {         0}, {   0} },       
};

SR__ s_105[] =
{
    { { REQ_DEF}, {  11} },       
    { {      43}, {  76} }, // '+'
    { {      45}, {  77} }, // '-'
    { {      42}, {  78} }, // '*'
    { {      47}, {  79} }, // '/'
    { {     273}, {  70} }, // LE 
    { {     275}, {  71} }, // GE 
    { {     274}, {  72} }, // LEQ
    { {     276}, {  73} }, // GEQ
    { {     271}, {  74} }, // EQ 
    { {     272}, {  75} }, // NEQ
    { {       0}, { -34} },       
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 91 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure(current_procedure, get_line_number());
         program_object.global_list_in_proc_check();
         }
         }
        break;

        case 2:
#line 104 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
#line 114 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
#line 127 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 5:
#line 141 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-3].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-3].string_value == "main"), "Procedure name must be main in declaration");
         }
         }
        break;

        case 6:
#line 184 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast* seq = d_vsp__[-1].sequence_ast;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((seq != NULL), "statement list cannot be null");
         current_procedure->set_sequence_ast(*seq);
         }
         }
        break;

        case 7:
#line 152 "parser.yy"
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-2].string_value == "main"), "Procedure name must be main");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         CHECK_INPUT ((program_object.variable_in_symbol_list_check(proc_name) == false),
         "Procedure name cannot be same as global variable", get_line_number());
         }
         }
        break;

        case 8:
#line 168 "parser.yy"
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 9:
#line 198 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 10:
#line 206 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 11:
#line 218 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Symbol_Table * decl_list = new Symbol_Table();
         vector<Symbol_Table_Entry *> ste_vec = *d_vsp__[0].symbl_tabl;
         for(int i = 0; i < (ste_vec).size(); i++)
         {
         Symbol_Table_Entry * decl_stmt = ste_vec[i];
         CHECK_INVARIANT((decl_stmt != NULL), "Non-terminal declaration statement cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT ((program_object.variable_proc_name_check(decl_name) == false),
         "Variable name cannot be same as the procedure name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         decl_list->push_symbol(decl_stmt);
         } 
         
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 12:
#line 251 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Symbol_Table * decl_list = d_vsp__[-1].symbol_table;
         vector<Symbol_Table_Entry *> ste_vec = *d_vsp__[0].symbl_tabl;
         CHECK_INVARIANT((decl_list != NULL), "The declaration statement list cannot be null");
         for(int i = 0; i < (ste_vec).size() ; i++ )
         {
         Symbol_Table_Entry * decl_stmt = (ste_vec)[i];
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((decl_list->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(decl_stmt);
         }
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 13:
#line 295 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-1].decl_vec != NULL), "Declaration cannot be null");
         
         vector<Symbol_Table_Entry *> * symbl_tabl = new vector<Symbol_Table_Entry *>();
         
         vector<pair<Data_Type, string>*> nlist = *d_vsp__[-1].decl_vec;
         for (int i = 0; i < nlist.size(); i++)
         {
         Symbol_Table_Entry * decl_entry = new Symbol_Table_Entry(nlist[i]->second, nlist[i]->first, get_line_number());
         
         symbl_tabl->push_back(decl_entry);
         }
         
         d_val__.symbl_tabl = symbl_tabl;
         }
         }
        break;

        case 14:
#line 324 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Data_Type type = int_data_type;
         vector<string> nlist = *d_vsp__[0].var_vec;
         vector<pair<Data_Type, string>*> *vlist = new vector<pair<Data_Type, string>*>();
         for(int i = 0; i < (nlist).size(); i++)
         {
         pair<Data_Type, string> * declr = new pair<Data_Type, string>(type, nlist[i]);
         vlist->push_back(declr); 
         }
         d_val__.decl_vec = vlist;
         }
         }
        break;

        case 15:
#line 344 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Data_Type type = double_data_type;
         vector<string> nlist = *d_vsp__[0].var_vec;
         vector<pair<Data_Type, string>*> * vlist = new vector<pair<Data_Type, string>*>();
         for(int i = 0; i < nlist.size(); i++)
         {
         pair<Data_Type, string> * declr = new pair<Data_Type, string>(type, nlist[i]);
         vlist->push_back(declr); 
         }
         d_val__.decl_vec = vlist;
         }
         }
        break;

        case 16:
#line 366 "parser.yy"
        {
         if(NOT_ONLY_PARSE)
         {
         vector<string> * vlist = new vector<string>();
         vlist->push_back(*d_vsp__[0].string_value);
         d_val__.var_vec = vlist; 
         }
         }
        break;

        case 17:
#line 379 "parser.yy"
        {
         if(NOT_ONLY_PARSE)
         {
         vector<string> * vlist = d_vsp__[-2].var_vec;
         vlist->push_back(*d_vsp__[0].string_value);
         d_val__.var_vec = vlist;
         }
         }
        break;

        case 18:
#line 394 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Sequence_Ast * stmt_list = new Sequence_Ast(get_line_number());
         
         d_val__.sequence_ast = stmt_list;
         }
         }
        break;

        case 19:
#line 406 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast * stmt_list = d_vsp__[-1].sequence_ast;
         Ast * stmt = d_vsp__[0].ast;
         
         
         
         stmt_list->ast_push_back(stmt);
         d_val__.sequence_ast = stmt_list;
         
         }
         }
        break;

        case 20:
#line 430 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 21:
#line 441 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         (d_val__.ast) = d_vsp__[-1].sequence_ast;
         }
         }
        break;

        case 22:
#line 452 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * cond = d_vsp__[-2].ast;
         Ast * body = d_vsp__[0].ast;
         
         Ast * loopstmt = new Iteration_Statement_Ast(cond, body,get_line_number(), false);
         d_val__.ast = loopstmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 23:
#line 467 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * cond = d_vsp__[-2].ast;
         Ast * then = d_vsp__[0].ast;
         
         Ast * sequence_ast = new Sequence_Ast(get_line_number());
         Ast * selectnstmt = new Selection_Statement_Ast(d_vsp__[-2].ast, d_vsp__[0].ast, sequence_ast, get_line_number());
         d_val__.ast = selectnstmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 24:
#line 485 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * cond = d_vsp__[-4].ast;
         Ast * then = d_vsp__[-2].ast;
         Ast * els = d_vsp__[0].ast;
         Ast * selectnstmt = new Selection_Statement_Ast(cond, then, els, get_line_number());
         d_val__.ast = selectnstmt;
         (d_val__.ast)->check_ast();; 
         
         }
         }
        break;

        case 25:
#line 504 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * cond = d_vsp__[-2].ast;
         Ast * body = d_vsp__[-5].ast;
         Ast * dowhile = new Iteration_Statement_Ast(cond, body, get_line_number(), true);
         d_val__.ast = dowhile;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 26:
#line 527 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-3].ast != NULL) && (d_vsp__[-1].ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-3].ast;
         Ast * right = d_vsp__[-1].ast;
         
         Assignment_Ast * assgn_stmt = new Assignment_Ast(left, right, get_line_number());
         
         
         
         d_val__.ast = assgn_stmt;
         
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 27:
#line 559 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].ast;
         Ast * right = d_vsp__[0].ast;
         Arithmetic_Expr_Ast * plus_stmt = new Plus_Ast(left, right, get_line_number());
         d_val__.ast = plus_stmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 28:
#line 576 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].ast;
         Ast * right = d_vsp__[0].ast;
         Arithmetic_Expr_Ast * minus_stmt = new Minus_Ast(left, right, get_line_number());
         d_val__.ast = minus_stmt;
         
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 29:
#line 594 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].ast;
         Ast * right = d_vsp__[0].ast;
         Arithmetic_Expr_Ast * mult_stmt = new Mult_Ast(left, right, get_line_number());
         d_val__.ast = mult_stmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 30:
#line 611 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-2].ast != NULL) && (d_vsp__[0].ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].ast;
         Ast * right = d_vsp__[0].ast;
         Arithmetic_Expr_Ast * divide_stmt = new Divide_Ast(left, right, get_line_number());
         d_val__.ast = divide_stmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 31:
#line 628 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 32:
#line 638 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].ast != NULL), "lhs/rhs cannot be null");
         UMinus_Ast * uminus_stmt = new UMinus_Ast(d_vsp__[0].ast, NULL, get_line_number());
         d_val__.ast = uminus_stmt;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 33:
#line 651 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         
         }
         }
        break;

        case 34:
#line 663 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * condn_ast = new Conditional_Operator_Ast(d_vsp__[-4].ast, d_vsp__[-2].ast, d_vsp__[0].ast, get_line_number());
         d_val__.ast = condn_ast;
         (d_val__.ast)->check_ast();
         }
         }
        break;

        case 35:
#line 681 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, less_than, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 36:
#line 693 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, greater_than, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 37:
#line 705 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, less_equalto, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 38:
#line 717 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, greater_equalto, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 39:
#line 729 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, equalto, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 40:
#line 741 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * reltn_expr = new Relational_Expr_Ast(d_vsp__[-2].ast, not_equalto, d_vsp__[0].ast, get_line_number());
         d_val__.ast = reltn_expr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 41:
#line 754 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * boolexpr = new Boolean_Expr_Ast(d_vsp__[-2].ast, boolean_or, d_vsp__[0].ast, get_line_number());
         d_val__.ast = boolexpr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 42:
#line 766 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * boolexpr = new Boolean_Expr_Ast(d_vsp__[-2].ast, boolean_and, d_vsp__[0].ast, get_line_number());
         d_val__.ast = boolexpr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 43:
#line 778 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Ast * boolexpr = new Boolean_Expr_Ast(NULL, boolean_not, d_vsp__[0].ast, get_line_number());
         d_val__.ast = boolexpr;
         (d_val__.ast)->check_ast();;
         }
         }
        break;

        case 44:
#line 790 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[-1].ast;
         }
         }
        break;

        case 45:
#line 799 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 46:
#line 814 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 47:
#line 823 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 48:
#line 834 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value));
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(program_object.get_symbol_table_entry(*d_vsp__[0].string_value));
         else
         CHECK_INPUT_AND_ABORT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, *var_table_entry, get_line_number());
         delete d_vsp__[0].string_value;
         }
         }
        break;

        case 49:
#line 859 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

        case 50:
#line 870 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<double>(d_vsp__[0].double_value, double_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



