// Generated by Bisonc++ V4.10.01 on Fri, 03 Mar 2017 15:37:29 +0530

#ifndef ParserBase_h_included
#define ParserBase_h_included

#include <exception>
#include <vector>
#include <iostream>


namespace // anonymous
{
    struct PI__;
}



class ParserBase
{
    public:
// $insert tokens

    // Symbolic tokens:
    enum Tokens__
    {
        INTEGER_NUMBER = 257,
        NAME,
        DOUBLE_NUMBER,
        RETURN,
        INTEGER,
        FLOAT,
        ASSIGN,
        VOID,
        IF,
        WHILE,
        DO,
        SAATH,
        OR,
        AND,
        EQ,
        NEQ,
        LE,
        LEQ,
        GE,
        GEQ,
        UMINUS,
        NOT,
        IFX,
        ELSE,
    };

// $insert STYPE
union STYPE__
{
 
 int integer_value;
 double double_value;
 std::string * string_value;
 Procedure * procedure;
 pair<Data_Type, string> * decl;
 Sequence_Ast * sequence_ast;
 Symbol_Table * symbol_table;
 
 vector<string> * var_vec;
 vector<pair<Data_Type, string>*> * decl_vec;
 vector<Symbol_Table_Entry *> * symbl_tabl;
 Ast * ast;
 Assignment_Ast * asmt_ast;
 Arithmetic_Expr_Ast * arthmexpr_ast;
 Relational_Expr_Ast * reltnexpr_ast;
 Boolean_Expr_Ast * boolexpr_ast;
 Selection_Statement_Ast * selecstmt_ast;
 Iteration_Statement_Ast * itrnstmt_ast;
 Conditional_Operator_Ast * condn_Ast;
};


    private:
        int d_stackIdx__;
        std::vector<size_t>   d_stateStack__;
        std::vector<STYPE__>  d_valueStack__;

    protected:
        enum Return__
        {
            PARSE_ACCEPT__ = 0,   // values used as parse()'s return values
            PARSE_ABORT__  = 1
        };
        enum ErrorRecovery__
        {
            DEFAULT_RECOVERY_MODE__,
            UNEXPECTED_TOKEN__,
        };
        bool        d_debug__;
        size_t      d_nErrors__;
        size_t      d_requiredTokens__;
        size_t      d_acceptedTokens__;
        int         d_token__;
        int         d_nextToken__;
        size_t      d_state__;
        STYPE__    *d_vsp__;
        STYPE__     d_val__;
        STYPE__     d_nextVal__;

        ParserBase();

        void ABORT() const;
        void ACCEPT() const;
        void ERROR() const;
        void clearin();
        bool debug() const;
        void pop__(size_t count = 1);
        void push__(size_t nextState);
        void popToken__();
        void pushToken__(int token);
        void reduce__(PI__ const &productionInfo);
        void errorVerbose__();
        size_t top__() const;

    public:
        void setDebug(bool mode);
}; 

inline bool ParserBase::debug() const
{
    return d_debug__;
}

inline void ParserBase::setDebug(bool mode)
{
    d_debug__ = mode;
}

inline void ParserBase::ABORT() const
{
    throw PARSE_ABORT__;
}

inline void ParserBase::ACCEPT() const
{
    throw PARSE_ACCEPT__;
}

inline void ParserBase::ERROR() const
{
    throw UNEXPECTED_TOKEN__;
}


// As a convenience, when including ParserBase.h its symbols are available as
// symbols in the class Parser, too.
#define Parser ParserBase


#endif


