// Generated by Bisonc++ V4.10.01 on Fri, 03 Feb 2017 15:08:47 +0530

// $insert class.ih
#include "parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum 
    {
        STACK_EXPANSION = 5     // size to expand the state-stack with when
                                // full
    };

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {276, 2}, // 1: program ->  declaration_list procedure_definition
     {277, 1}, // 2: declaration_list ->  procedure_declaration
     {277, 2}, // 3: declaration_list ->  variable_declaration_list procedure_declaration
     {277, 2}, // 4: declaration_list ->  procedure_declaration variable_declaration_list
     {279, 5}, // 5: procedure_declaration (VOID) ->  VOID NAME '(' ')' ';'
     {278, 9}, // 6: procedure_definition (NAME) ->  NAME '(' ')' #0001 '{' optional_variable_declaration_list #0002 statement_list '}'
     {280, 0}, // 7: #0001 ->  <empty>
     {281, 0}, // 8: #0002 ->  <empty>
     {282, 0}, // 9: optional_variable_declaration_list ->  <empty>
     {282, 1}, // 10: optional_variable_declaration_list ->  variable_declaration_list
     {283, 1}, // 11: variable_declaration_list ->  variable_declaration
     {283, 2}, // 12: variable_declaration_list ->  variable_declaration_list variable_declaration
     {284, 2}, // 13: variable_declaration (';') ->  declaration ';'
     {285, 2}, // 14: declaration (INTEGER) ->  INTEGER NAME
     {285, 2}, // 15: declaration (FLOAT) ->  FLOAT NAME
     {286, 0}, // 16: statement_list ->  <empty>
     {286, 2}, // 17: statement_list ->  statement_list assignment_statement
     {287, 4}, // 18: assignment_statement (ASSIGN) ->  variable ASSIGN arith_expression ';'
     {288, 3}, // 19: arith_expression ('+') ->  arith_expression '+' arith_expression
     {288, 3}, // 20: arith_expression ('-') ->  arith_expression '-' arith_expression
     {288, 3}, // 21: arith_expression ('*') ->  arith_expression '*' arith_expression
     {288, 3}, // 22: arith_expression ('/') ->  arith_expression '/' arith_expression
     {288, 2}, // 23: arith_expression (UMINUS) ->  '-' arith_expression
     {288, 3}, // 24: arith_expression ('(') ->  '(' arith_expression ')'
     {288, 1}, // 25: arith_expression ->  expression_term
     {289, 1}, // 26: expression_term ->  variable
     {289, 1}, // 27: expression_term ->  constant
     {290, 1}, // 28: variable (NAME) ->  NAME
     {291, 1}, // 29: constant (INTEGER_NUMBER) ->  INTEGER_NUMBER
     {291, 1}, // 30: constant (DOUBLE_NUMBER) ->  DOUBLE_NUMBER
     {292, 1}, // 31: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 10} },                             
    { {       276}, {  1} }, // program                  
    { {       277}, {  2} }, // declaration_list         
    { {       279}, {  3} }, // procedure_declaration    
    { {       283}, {  4} }, // variable_declaration_list
    { {       264}, {  5} }, // VOID                     
    { {       284}, {  6} }, // variable_declaration     
    { {       285}, {  7} }, // declaration              
    { {       261}, {  8} }, // INTEGER                  
    { {       262}, {  9} }, // FLOAT                    
    { {         0}, {  0} },                             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, {  3} },                        
    { {       278}, { 10} }, // procedure_definition
    { {       258}, { 11} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                             
    { {     283}, { 12} }, // variable_declaration_list
    { {     284}, {  6} }, // variable_declaration     
    { {     285}, {  7} }, // declaration              
    { {     261}, {  8} }, // INTEGER                  
    { {     262}, {  9} }, // FLOAT                    
    { {       0}, { -2} },                             
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, {  7} },                         
    { {       279}, { 13} }, // procedure_declaration
    { {       284}, { 14} }, // variable_declaration 
    { {       264}, {  5} }, // VOID                 
    { {       285}, {  7} }, // declaration          
    { {       261}, {  8} }, // INTEGER              
    { {       262}, {  9} }, // FLOAT                
    { {         0}, {  0} },                         
};

SR__ s_5[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 15} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_6[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 16} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 17} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       258}, { 18} }, // NAME
    { {         0}, {  0} },        
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 19} }, // '('
    { {         0}, {  0} },       
};

SR__ s_12[] =
{
    { { REQ_DEF}, {  5} },                        
    { {     284}, { 14} }, // variable_declaration
    { {     285}, {  7} }, // declaration         
    { {     261}, {  8} }, // INTEGER             
    { {     262}, {  9} }, // FLOAT               
    { {       0}, { -4} },                        
};

SR__ s_13[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_14[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        40}, { 20} }, // '('
    { {         0}, {  0} },       
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_19[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 21} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        41}, { 22} }, // ')'
    { {         0}, {  0} },       
};

SR__ s_21[] =
{
    { { DEF_RED}, {  2} },         
    { {     280}, { 23} }, // #0001
    { {       0}, { -7} },         
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {        59}, { 24} }, // ';'
    { {         0}, {  0} },       
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },       
    { {       123}, { 25} }, // '{'
    { {         0}, {  0} },       
};

SR__ s_24[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_25[] =
{
    { { REQ_DEF}, {  7} },                                      
    { {     282}, { 26} }, // optional_variable_declaration_list
    { {     283}, { 27} }, // variable_declaration_list         
    { {     284}, {  6} }, // variable_declaration              
    { {     285}, {  7} }, // declaration                       
    { {     261}, {  8} }, // INTEGER                           
    { {     262}, {  9} }, // FLOAT                             
    { {       0}, { -9} },                                      
};

SR__ s_26[] =
{
    { { DEF_RED}, {  2} },         
    { {     281}, { 28} }, // #0002
    { {       0}, { -8} },         
};

SR__ s_27[] =
{
    { { REQ_DEF}, {   5} },                        
    { {     284}, {  14} }, // variable_declaration
    { {     285}, {   7} }, // declaration         
    { {     261}, {   8} }, // INTEGER             
    { {     262}, {   9} }, // FLOAT               
    { {       0}, { -10} },                        
};

SR__ s_28[] =
{
    { { DEF_RED}, {   2} },                  
    { {     286}, {  29} }, // statement_list
    { {       0}, { -16} },                  
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  5} },                        
    { {       125}, { 30} }, // '}'                 
    { {       287}, { 31} }, // assignment_statement
    { {       290}, { 32} }, // variable            
    { {       258}, { 33} }, // NAME                
    { {         0}, {  0} },                        
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       263}, { 34} }, // ASSIGN
    { {         0}, {  0} },          
};

SR__ s_33[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 35} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, {  6} },       
    { {        59}, { 43} }, // ';'
    { {        43}, { 44} }, // '+'
    { {        45}, { 45} }, // '-'
    { {        42}, { 46} }, // '*'
    { {        47}, { 47} }, // '/'
    { {         0}, {  0} },       
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 48} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 49} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_43[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 50} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 51} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 52} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, { 10} },                    
    { {       288}, { 53} }, // arith_expression
    { {        45}, { 36} }, // '-'             
    { {        40}, { 37} }, // '('             
    { {       289}, { 38} }, // expression_term 
    { {       290}, { 39} }, // variable        
    { {       291}, { 40} }, // constant        
    { {       258}, { 33} }, // NAME            
    { {       257}, { 41} }, // INTEGER_NUMBER  
    { {       259}, { 42} }, // DOUBLE_NUMBER   
    { {         0}, {  0} },                    
};

SR__ s_48[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  6} },       
    { {        41}, { 54} }, // ')'
    { {        43}, { 44} }, // '+'
    { {        45}, { 45} }, // '-'
    { {        42}, { 46} }, // '*'
    { {        47}, { 47} }, // '/'
    { {         0}, {  0} },       
};

SR__ s_50[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  46} }, // '*'
    { {      47}, {  47} }, // '/'
    { {       0}, { -19} },       
};

SR__ s_51[] =
{
    { { REQ_DEF}, {   3} },       
    { {      42}, {  46} }, // '*'
    { {      47}, {  47} }, // '/'
    { {       0}, { -20} },       
};

SR__ s_52[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_53[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_54[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,
};

} // anonymous namespace ends



// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    d_stackIdx__(-1),
    // $insert debuginit
    d_debug__(false),
    d_nErrors__(0),
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    if (static_cast<size_t>(d_stackIdx__ + 1) == d_stateStack__.size())
    {
        size_t newSize = d_stackIdx__ + STACK_EXPANSION;
        d_stateStack__.resize(newSize);
        d_valueStack__.resize(newSize);
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = d_val__;
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = d_nextVal__;
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = d_val__;
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

                                    // save default non-nested block $$
    if (int size = s_productionInfo[production].d_size)
        d_val__ = d_vsp__[1 - size];

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 58 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         program_object.set_procedure(current_procedure, get_line_number());
         program_object.global_list_in_proc_check();
         }
         }
        break;

        case 2:
#line 71 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = new Symbol_Table();
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 3:
#line 81 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 4:
#line 94 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table * global_table = d_vsp__[0].symbol_table;
         CHECK_INVARIANT((global_table != NULL), "Global declarations cannot be null");
         program_object.set_global_table(*global_table);
         }
         }
        break;

        case 5:
#line 108 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-3].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-3].string_value == "main"), "Procedure name must be main in declaration");
         }
         }
        break;

        case 6:
#line 151 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Sequence_Ast* seq = d_vsp__[-1].sequence_ast;
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         CHECK_INVARIANT((seq != NULL), "statement list cannot be null");
         current_procedure->set_sequence_ast(*seq);
         }
         }
        break;

        case 7:
#line 119 "parser.yy"
        d_val__ = d_vsp__[-2];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[-2].string_value != NULL), "Procedure name cannot be null");
         CHECK_INVARIANT((*d_vsp__[-2].string_value == "main"), "Procedure name must be main");
         string proc_name = *d_vsp__[-2].string_value;
         current_procedure = new Procedure(void_data_type, proc_name, get_line_number());
         CHECK_INPUT ((program_object.variable_in_symbol_list_check(proc_name) == false),
         "Procedure name cannot be same as global variable", get_line_number());
         }
         }
        break;

        case 8:
#line 135 "parser.yy"
        d_val__ = d_vsp__[-5];
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((current_procedure != NULL), "Current procedure cannot be null");
         Symbol_Table * local_table = d_vsp__[0].symbol_table;
         if (local_table == NULL)
         local_table = new Symbol_Table();
         current_procedure->set_local_list(*local_table);
         }
         }
        break;

        case 9:
#line 165 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.symbol_table = NULL;
         }
         }
        break;

        case 10:
#line 173 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].symbol_table != NULL), "Declaration statement list cannot be null here");
         d_val__.symbol_table = d_vsp__[0].symbol_table;
         }
         }
        break;

        case 11:
#line 185 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         CHECK_INVARIANT((decl_stmt != NULL), "Non-terminal declaration statement cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT ((program_object.variable_proc_name_check(decl_name) == false),
         "Variable name cannot be same as the procedure name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         Symbol_Table * decl_list = new Symbol_Table();
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 12:
#line 210 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         
         Symbol_Table_Entry * decl_stmt = d_vsp__[0].symbol_entry;
         Symbol_Table * decl_list = d_vsp__[-1].symbol_table;
         CHECK_INVARIANT((decl_stmt != NULL), "The declaration statement cannot be null");
         CHECK_INVARIANT((decl_list != NULL), "The declaration statement list cannot be null");
         string decl_name = decl_stmt->get_variable_name();
         CHECK_INPUT((program_object.variable_proc_name_check(decl_name) == false),
         "Procedure name cannot be same as the variable name", get_line_number());
         if(current_procedure != NULL)
         {
         CHECK_INPUT((current_procedure->get_proc_name() != decl_name),
         "Variable name cannot be same as procedure name", get_line_number());
         }
         CHECK_INPUT((decl_list->variable_in_symbol_list_check(decl_name) == false), 
         "Variable is declared twice", get_line_number());
         decl_list->push_symbol(decl_stmt);
         d_val__.symbol_table = decl_list;
         }
         }
        break;

        case 13:
#line 242 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         pair<Data_Type, string> * decl = d_vsp__[-1].decl;
         CHECK_INVARIANT((decl != NULL), "Declaration cannot be null");
         Data_Type type = decl->first;
         string decl_name = decl->second;
         Symbol_Table_Entry * decl_entry = new Symbol_Table_Entry(decl_name, type, get_line_number());
         d_val__.symbol_entry = decl_entry;
         }
         }
        break;

        case 14:
#line 262 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = int_data_type;
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         d_val__.decl = declar; }
         }
        break;

        case 15:
#line 277 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Name cannot be null");
         string name = *d_vsp__[0].string_value;
         Data_Type type = double_data_type;
         pair<Data_Type, string> * declar = new pair<Data_Type, string>(type, name);
         d_val__.decl = declar; }
         }
        break;

        case 16:
#line 293 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.sequence_ast = NULL; 
         }
         }
        break;

        case 17:
#line 302 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Sequence_Ast * stmt_list = d_vsp__[-1].sequence_ast;
         Ast * stmt = d_vsp__[0].asmt_ast;
         
         
         if (stmt_list == NULL ){
         stmt_list = new Sequence_Ast(get_line_number());
         }
         
         stmt_list->ast_push_back(stmt);
         d_val__.sequence_ast = stmt_list; 
         }
         }
        break;

        case 18:
#line 326 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         CHECK_INVARIANT(((d_vsp__[-3].ast != NULL) && (d_vsp__[-1].arthm_ast != NULL)), "lhs/rhs cannot be null");
         
         Ast * left = d_vsp__[-3].ast;
         Ast * right = d_vsp__[-1].arthm_ast;
         
         Assignment_Ast * assgn_stmt = new Assignment_Ast(left, right, get_line_number());
         
         
         
         
         
         d_val__.asmt_ast = assgn_stmt; 
         }
         }
        break;

        case 19:
#line 355 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].arthm_ast != NULL) && (d_vsp__[0].arthm_ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].arthm_ast;
         Ast * right = d_vsp__[0].arthm_ast;
         Arithmetic_Expr_Ast * plus_stmt = new Plus_Ast(left, right, get_line_number());
         d_val__.arthm_ast = plus_stmt;
         }
         }
        break;

        case 20:
#line 369 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].arthm_ast != NULL) && (d_vsp__[0].arthm_ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].arthm_ast;
         Ast * right = d_vsp__[0].arthm_ast;
         Arithmetic_Expr_Ast * minus_stmt = new Minus_Ast(left, right, get_line_number());
         d_val__.arthm_ast = minus_stmt;
         }
         }
        break;

        case 21:
#line 383 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].arthm_ast != NULL) && (d_vsp__[0].arthm_ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].arthm_ast;
         Ast * right = d_vsp__[0].arthm_ast;
         Arithmetic_Expr_Ast * mult_stmt = new Mult_Ast(left, right, get_line_number());
         d_val__.arthm_ast = mult_stmt;
         }
         }
        break;

        case 22:
#line 397 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT(((d_vsp__[-2].arthm_ast != NULL) && (d_vsp__[0].arthm_ast != NULL)), "lhs/rhs cannot be null");
         Ast * left = d_vsp__[-2].arthm_ast;
         Ast * right = d_vsp__[0].arthm_ast;
         Arithmetic_Expr_Ast * divide_stmt = new Divide_Ast(left, right, get_line_number());
         d_val__.arthm_ast = divide_stmt;
         }
         }
        break;

        case 23:
#line 412 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         CHECK_INVARIANT((d_vsp__[0].arthm_ast != NULL), "lhs/rhs cannot be null");
         UMinus_Ast * uminus_stmt = new UMinus_Ast(d_vsp__[0].arthm_ast, NULL, get_line_number());
         d_val__.arthm_ast = uminus_stmt;
         }
         }
        break;

        case 24:
#line 424 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.arthm_ast = (Arithmetic_Expr_Ast *) d_vsp__[-1].arthm_ast;
         }
         }
        break;

        case 25:
#line 432 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         d_val__.arthm_ast = (Arithmetic_Expr_Ast *) d_vsp__[0].ast;
         }
         }
        break;

        case 26:
#line 456 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 27:
#line 465 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         d_val__.ast = d_vsp__[0].ast;
         }
         }
        break;

        case 28:
#line 476 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         Symbol_Table_Entry * var_table_entry;
         CHECK_INVARIANT((d_vsp__[0].string_value != NULL), "Variable name cannot be null");
         if (current_procedure->variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(current_procedure->get_symbol_table_entry(*d_vsp__[0].string_value));
         else if (program_object.variable_in_symbol_list_check(*d_vsp__[0].string_value))
         var_table_entry = &(program_object.get_symbol_table_entry(*d_vsp__[0].string_value));
         else
         CHECK_INPUT_AND_ABORT(CONTROL_SHOULD_NOT_REACH, "Variable has not been declared", get_line_number());
         d_val__.ast = new Name_Ast(*d_vsp__[0].string_value, *var_table_entry, get_line_number());
         delete d_vsp__[0].string_value;
         }
         }
        break;

        case 29:
#line 501 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<int>(d_vsp__[0].integer_value, int_data_type, get_line_number());
         d_val__.ast = num_ast;
         }
         }
        break;

        case 30:
#line 512 "parser.yy"
        {
         if (NOT_ONLY_PARSE)
         {
         
         Ast * num_ast = new Number_Ast<double>(d_vsp__[0].double_value, double_data_type, get_line_number());
         d_val__.ast = num_ast; }
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



